name: Build Everything, make artifact

on:
  workflow_dispatch:
  workflow_call:

jobs:
  # Single deploy job since we're just deploying
  build-rco3-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'RCO3Installer/pnpm-lock.yaml'
      - name: Install dependencies
        run: |
          cd RCO3Installer
          pnpm install
      - name: Build
        run: |
          cd RCO3Installer
          pnpm run build
      - name: Package
        run: |
          cd RCO3Installer
          pnpm run package
      - name: Make Artifact Dir
        run: |
          mkdir artifact
          mv RCO3Installer/dist/ artifact/installer-js
          mv RCO3Installer/bin/ artifact/installer-bin
          cp artifact/installer-bin/rco3installer-win.exe artifact/RCO2Installer.exe # upgrade from v2 to v3 installer
          echo $(sha512sum artifact/installer-js/index.js | cut -d ' ' -f 1) > artifact/installer-js/index.js.hash
      - name: Upload RCO3 Installers
        uses: actions/upload-artifact@v3
        with:
          name: rco3installer
          path: artifact
  build-rco3-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'rco-site/pnpm-lock.yaml'
      - name: Install dependencies
        run: |
          cd rco-site
          pnpm install
      - name: Build Site
        run: |
          cd rco-site
          pnpm build
      - name: Upload RCO3 Site
        uses: actions/upload-artifact@v3
        with:
          name: rco3site
          path: rco-site/build
  build-librco3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'LibRCO3/pnpm-lock.yaml'
      - name: Install dependencies
        run: |
          cd LibRCO3
          pnpm install
      - name: Build Site
        run: |
          cd LibRCO3
          pnpm build
      - name: Build Docs
        run: |
          cd LibRCO3
          pnpm build:docs
      - name: Upload RCO3 Library
        uses: actions/upload-artifact@v3
        with:
          name: librco3-dist
          path: LibRCO3/dist
      - name: Upload RCO3 Docs
        uses: actions/upload-artifact@v3
        with:
          name: librco3-docs
          path: LibRCO3/docs
  build-rco3:
    needs: [build-librco3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download LibRCO3
        uses: actions/download-artifact@v3
        with:
          name: librco3-dist
          path: LibRCO3/dist
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'RCO3/pnpm-lock.yaml'
      - name: Install dependencies of LibRCO3
        run: |
          cd LibRCO3
          pnpm i
      - name: Install dependencies
        run: |
          cd RCO3
          pnpm i
      - name: Build
        run: |
          cd RCO3
          pnpm build
      - name: Zip
        run: |
          cd RCO3
          mv dist RCO-JS
          zip RCO.zip RCO-JS/**/* RCO-JS/*
          cd ..
          mv RCO3/RCO.zip ./RCO.zip
      - name: Deploy RCO3
        uses: actions/upload-artifact@v3
        with:
          name: rco3
          path: RCO.zip
  build-rco3-launcher:
    # use matrix for os
    runs-on: ${{matrix.os == 'linux' && 'ubuntu-latest' || matrix.os == 'macos-intel' && 'macos-latest' || matrix.os == 'macos-apple' && 'macos-latest' || matrix.os == 'windows' && 'windows-latest'}}
    strategy:
      matrix:
        os: [linux, macos-intel, macos-apple, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Rust Target
        id: rust-launcher-cache
        uses: actions/cache@v3
        with:
          path: RCO3Launcher/target
          key: ${{ matrix.os }}-rco-launcher-rust-target-cache
      - name: Build Linux
        if: matrix.os == 'linux'
        run: |
          cd RCO3Launcher
          rustup target add x86_64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-gnu/release/rco3launcher ./rco3launcher-linux-x86_64
      - name: Build Windows
        if: matrix.os == 'windows'
        run: |
          cd RCO3Launcher
          rustup target add x86_64-pc-windows-gnu
          cargo build --release --target x86_64-pc-windows-gnu
          move target/x86_64-pc-windows-gnu/release/rco3launcher.exe rco3launcher-win32-x86_64.exe
      - name: Build Mac (Intel x86_64)
        if: matrix.os == 'macos-intel'
        run: |
          cd RCO3Launcher
          rustup target add x86_64-apple-darwin
          cargo build --release --target x86_64-apple-darwin
          mv target/x86_64-apple-darwin/release/rco3launcher ./rco3launcher-darwin-x86_64
      - name: Build Mac (Apple Silicon)
        if: matrix.os == 'macos-apple'
        run: |
          cd RCO3Launcher
          rustup target add aarch64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
          mv target/aarch64-apple-darwin/release/rco3launcher ./rco3launcher-darwin-arm64
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: rco3launcher-${{matrix.os}}
          path: RCO3Launcher/rco3launcher-*
  upload-static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create RCO ClientAppSettings Hash
        run: |
          echo $(sha512sum assets/ClientAppSettings.json | cut -d ' ' -f 1) > assets/ClientAppSettings.json.sha512
          echo $(sha256sum assets/ClientAppSettings.json | cut -d ' ' -f 1) > assets/ClientAppSettings.json.sha256
          echo $(md5sum assets/ClientAppSettings.json | cut -d ' ' -f 1) > assets/ClientAppSettings.json.md5
      - name: Deploy Static
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: assets
  merge-rco3-launcher:
    runs-on: ubuntu-latest
    needs: [build-rco3-launcher]
    steps:
      - name: Download RCO3 Launcher Linux
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher-linux
          path: launcher
      - name: Download RCO3 Launcher Windows
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher-windows
          path: launcher
      - name: Download RCO3 Launcher Mac (Intel x86_64)
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher-macos-intel
          path: launcher
      - name: Download RCO3 Launcher Mac (Apple Silicon)
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher-macos-apple
          path: launcher
      - name: Hash
        run: |
          sha512sum launcher/rco3launcher-* > launcher/rco3launcher.sha512
      - name: Upload RCO3 Launcher
        uses: actions/upload-artifact@v3
        with:
          name: rco3launcher
          path: .
  merge-builds:
    runs-on: ubuntu-latest
    needs: [build-rco3-installer, build-rco3-site, build-rco3, build-librco3, upload-static, merge-rco3-launcher]
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Make Directories
        run:
          mkdir lib
      - name: Download RCO3 Site
        uses: actions/download-artifact@v3
        with:
          name: rco3site
          path: .
      - name: Download RCO3 Installer
        uses: actions/download-artifact@v3
        with:
          name: rco3installer
          path: .
      - name: Download RCO3
        uses: actions/download-artifact@v3
        with:
          name: rco3
          path: .
      - name: Download LibRCO3
        uses: actions/download-artifact@v3
        with:
          name: librco3-dist
          path: lib/dist
      - name: Download LibRCO3 Documentation
        uses: actions/download-artifact@v3
        with:
          name: librco3-docs
          path: lib/docs
      - name: Download RCO3Launcher
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher
          path: .
      - name: Unzip
        run: |
          unzip -u RCO.zip
          rm RCO.zip
      - name: Download Assets
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: .
      - name: Create Important Hashes
        run: |
          sha512sum RCO.exe > RCOVersion
          sha512sum RCO2Installer.exe > RCO2Installer.hash
          sha512sum RCO-JS/* > RCO-JS/sha512sum.txt
          find . -type f -print0 | xargs -0 sha512sum | sha512sum > deployment.hash
      - name: Temp - Rename RCO-Legacy-Installer.exe to RCO2Installer.exe
        run: |
          find
          mv RCO2Installer.exe RCONextGen-Installer.exe
          mv RCO-Legacy-Installer.exe RCO2Installer.exe
      - name: Create Indexes where missing
        run: |
          pnpm create @3xpo/index build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: page
          path: .
