name: Build Everything, make artifact

on:
  push:
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  build-rco3-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'RCO3Installer/pnpm-lock.yaml'
      - name: Install dependencies
        run: |
          cd RCO3Installer
          pnpm install
      - name: Build
        run: |
          cd RCO3Installer
          pnpm run build
      - name: Package
        run: |
          cd RCO3Installer
          pnpm run package
      - name: Make Artifact Dir
        run: |
          mkdir artifact
          mv RCO2Installer.exe artifact/RCO-Legacy-Installer.exe
          mv RCO3Installer/dist/ artifact/installer-js
          mv RCO3Installer/bin/ artifact/installer-bin
          echo $(sha512sum artifact/installer-js/index.js | cut -d ' ' -f 1) > artifact/installer-js/index.js.hash
      - name: Upload RCO3 Installers
        uses: actions/upload-artifact@v3
        with:
          name: rco3installer
          path: artifact
  build-rco3-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'rco-site/pnpm-lock.yaml'
      - name: Install dependencies
        run: |
          cd rco-site
          pnpm install
      - name: Build Site
        run: |
          cd rco-site
          pnpm build
      - name: Upload RCO3 Site
        uses: actions/upload-artifact@v3
        with:
          name: rco3site
          path: rco-site/build
  build-rco3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip & Move (temp)
        run: |
          zip RCO.zip RCO.exe
      - name: Deploy RCO3
        uses: actions/upload-artifact@v3
        with:
          name: rco3
          path: RCO.zip
  upload-static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create RCO ClientAppSettings Hash
        run: |
          echo $(sha512sum assets/ClientAppSettings.json | cut -d ' ' -f 1) > assets/ClientAppSettings.json.sha512
          echo $(sha256sum assets/ClientAppSettings.json | cut -d ' ' -f 1) > assets/ClientAppSettings.json.sha256
          echo $(md5sum assets/ClientAppSettings.json | cut -d ' ' -f 1) > assets/ClientAppSettings.json.md5
      - name: Deploy Static
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: assets
  merge-builds:
    runs-on: ubuntu-latest
    needs: [build-rco3-installer, build-rco3-site, build-rco3, upload-static]
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Download RCO3 Site
        uses: actions/download-artifact@v3
        with:
          name: rco3site
          path: .
      - name: Download RCO3 Installer
        uses: actions/download-artifact@v3
        with:
          name: rco3installer
          path: .
      - name: Download RCO3
        uses: actions/download-artifact@v3
        with:
          name: rco3
          path: .
      - name: Unzip
        run: |
          unzip RCO.zip
          rm RCO.zip
      - name: Download Assets
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: .
      - name: List Artifact
        run: find
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: page
          path: .
