name: Call On PR Actions

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  list-deployment-files:
    needs: build
    uses: ./.github/workflows/list-deployment-files.yml
