name: Test Pull Deploy

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download RCO3 Site
        uses: actions/download-artifact@v3
        with:
          name: page
          path: .
      - name: ls
        run: ls