name: Build Everything, make artifact

on:
  push:
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy RCO2 to Pages
        run: |
          ls
          mkdir pages
          mv ./RCO.exe pages/RCO.exe
          mv ./RCO2Installer.exe pages/RCO-Legacy-Installer.exe
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install dependencies
        run: |
          cd RCO3Installer
          pnpm install
      - name: Build
        run: |
          cd RCO3Installer
          pnpm run build
      - name: Package
        run: |
          cd RCO3Installer
          pnpm run package
      - name: Copy RCO3 to Pages
        run: |
          cp RCO3Installer/bin/rco3installer-win.exe pages/RCO2Installer.exe
          cp RCO3Installer/bin/rco3installer-win.exe pages/RCO3Installer-win.exe
          cp RCO3Installer/bin/rco3installer-macos pages/RCO3Installer-mac
          cp RCO3Installer/bin/rco3installer-linux pages/RCO3Installer-linux
          mv RCO3Installer/bin pages/RCO3Installer
          mv RCO3Installer/dist pages/RCO3Installer-js
      - name: Copy misc files to Pages
        run: |
          cp ClientAppSettings.json pages/
          cp hosts pages/
          cp programversion.rco pages/ # TODO: Replace this with a file from the build
          cp flagversion.rco pages/ # DEPRECATED: Hash will be used in future
      - name: Write hash of ClientAppSettings to pages
        run: |
          echo $(sha512sum ClientAppSettings.json | cut -d ' ' -f 1) > pages/ClientAppSettings.hash
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: page
          path: pages
